// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/_locales/en/messages.json"
    | "/_locales/ko/messages.json"
    | "/background.js"
    | "/icon/128.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/png/diagram-logo.png"
    | "/png/text-logo.png"
    | "/popup.html"
    | "/wxt.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
