name: Bug Report
description: Report a bug
labels:
  - bug

body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior

  - type: textarea
    id: environment
    attributes:
      label: Environment
