-- V1__init.sql (PostgreSQL)
-- 기본 가정:
-- - 모든 PK는 bigint identity
-- - created_at/updated_at은 timestamp (timezone 여부는 팀 정책에 따라 선택)

BEGIN;

-- 1) users
CREATE TABLE IF NOT EXISTS users (
                                     id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email       VARCHAR(255) NOT NULL,
    name        VARCHAR(255),
    avatar      VARCHAR(255),
    created_at  TIMESTAMP NOT NULL,
    role        VARCHAR(50) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
    );

-- 2) accounts
CREATE TABLE IF NOT EXISTS accounts (
                                        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        email          VARCHAR(255) NOT NULL,
    name           VARCHAR(255),
    provider       VARCHAR(50) NOT NULL,
    password_hash  VARCHAR(255),
    user_id        BIGINT,
    created_at     TIMESTAMP NOT NULL,
    CONSTRAINT uk_accounts_email_provider UNIQUE (email, provider),
    CONSTRAINT fk_accounts_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
    );

-- 3) category
CREATE TABLE IF NOT EXISTS category (
                                        id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        title    VARCHAR(255) NOT NULL,
    color    VARCHAR(7) NOT NULL,
    user_id  BIGINT,
    CONSTRAINT fk_category_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE SET NULL
    );

-- 4) tag
CREATE TABLE IF NOT EXISTS tag (
                                   id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name     VARCHAR(50) NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT fk_tag_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE,
    CONSTRAINT uk_tag_user UNIQUE (name, user_id)
    );

-- 5) note
CREATE TABLE IF NOT EXISTS note (
                                    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    title        TEXT NOT NULL,
                                    sub_title    VARCHAR(255),
    description  TEXT,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP,
    category_id  BIGINT,
    user_id      BIGINT NOT NULL,
    CONSTRAINT fk_note_category
    FOREIGN KEY (category_id) REFERENCES category(id)
    ON DELETE SET NULL,
    CONSTRAINT fk_note_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
    );

-- 6) note_tag (복합 PK)
CREATE TABLE IF NOT EXISTS note_tag (
                                        note_id BIGINT NOT NULL,
                                        tag_id  BIGINT NOT NULL,
                                        PRIMARY KEY (note_id, tag_id),
    CONSTRAINT fk_note_tag_note
    FOREIGN KEY (note_id) REFERENCES note(id)
    ON DELETE CASCADE,
    CONSTRAINT fk_note_tag_tag
    FOREIGN KEY (tag_id) REFERENCES tag(id)
    ON DELETE CASCADE
    );

-- 7) require
CREATE TABLE IF NOT EXISTS require (
                                       id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       user_id       BIGINT NOT NULL,
                                       require_type  VARCHAR(32) NOT NULL,
    title         VARCHAR(100) NOT NULL,
    description   TEXT NOT NULL,
    status        VARCHAR(32) NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP,
    CONSTRAINT fk_require_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
    );

-- 8) image (JOINED 상속의 부모 테이블)
CREATE TABLE IF NOT EXISTS image (
                                     id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     image_type   VARCHAR(31) NOT NULL,
    url          VARCHAR(1024) NOT NULL,
    origin_name  VARCHAR(255) NOT NULL,
    extension    VARCHAR(50) NOT NULL,
    size         BIGINT NOT NULL,
    created_at   TIMESTAMP NOT NULL,
    deleted_at   TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS idx_image_deleted_at ON image (deleted_at);

-- 9) note_image (JOINED 상속 자식 테이블)
-- 부모(image)의 id를 그대로 PK로 공유해야 하므로 identity를 쓰면 안 됨
CREATE TABLE IF NOT EXISTS note_image (
                                          id       BIGINT PRIMARY KEY,
                                          note_id  BIGINT,
                                          CONSTRAINT fk_note_image_image
                                          FOREIGN KEY (id) REFERENCES image(id)
    ON DELETE CASCADE,
    CONSTRAINT fk_note_image_note
    FOREIGN KEY (note_id) REFERENCES note(id)
    ON DELETE CASCADE
    );

COMMIT;
